    version: '2.4'
    services:
      vault:
        image: vault:latest
        container_name: vault
        ports:
          - 8080:8200
        volumes:
          - .\config:c:\vault\config
          - .\file:c:\vault\file
          - .\logs:c:\logs
        restart: unless-stopped